# Generated by Django 3.0.3 on 2020-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=25, unique=True)),
                ('urun_adi', models.CharField(max_length=150)),
                ('urun_yabanci_adi', models.CharField(max_length=150)),
                ('kdv', models.FloatField(choices=[(0.0, 'Yok'), (0.01, 'K.D.V. %1'), (0.08, 'K.D.V. %8'), (0.18, 'K.Dv. %18')])),
            ],
        ),
    ]
