# Generated by Django 3.0.3 on 2020-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='urunler'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kdv',
            field=models.FloatField(choices=[(0.0, 'Yok'), (0.01, 'K.D.V. %1'), (0.08, 'K.D.V. %8'), (0.18, 'K.D.V. %18')]),
        ),
    ]
